// Mock data for the PM hub. Solo developer scenario — multiple projects, each with its own features.
// Hierarchy: Project ▸ Feature ▸ Ticket ▸ Session.
// Auto-IDs: PRJ-## are projects, FEAT-### are features, TMX-#### are tickets. Branches are derived.

const NOW = new Date('2026-04-25T14:30:00Z');

// Projects — root-level. Each has its own feature set, milestones, and identity.
const PROJECTS = [
  {
    id: 'PRJ-01',
    slug: 'tmux-agent',
    name: 'tmux-agent',
    tagline: 'Local agent runner inside tmux',
    description: 'A solo-dev orchestrator for running multiple Claude/Codex sessions in tmux panes, each bound to a feature\'s context bundle.',
    accent: 'iris',
    status: 'active',
    repo: 'github.com/you/tmux-agent',
    icon: '◇',
    pinned: true,
    lastTouched: '12m ago',
    activeFeatures: 3,
    totalFeatures: 5,
    liveSessions: 4,
    openTickets: 9,
  },
  {
    id: 'PRJ-02',
    slug: 'sift',
    name: 'sift',
    tagline: 'Local-first log search',
    description: 'A grep-meets-OpenSearch tool: index every project log directory locally, query with structured filters, no daemon.',
    accent: 'amber',
    status: 'active',
    repo: 'github.com/you/sift',
    icon: '⌗',
    pinned: true,
    lastTouched: '2d ago',
    activeFeatures: 1,
    totalFeatures: 4,
    liveSessions: 0,
    openTickets: 6,
  },
  {
    id: 'PRJ-03',
    slug: 'paper-cuts',
    name: 'paper-cuts',
    tagline: 'Personal site + writing',
    description: 'Static site generator + essays. Mostly content; occasional engine work when a post needs a new layout.',
    accent: 'mint',
    status: 'maintenance',
    repo: 'github.com/you/paper-cuts',
    icon: '✺',
    pinned: false,
    lastTouched: '6d ago',
    activeFeatures: 0,
    totalFeatures: 2,
    liveSessions: 0,
    openTickets: 2,
  },
  {
    id: 'PRJ-04',
    slug: 'ledger-mini',
    name: 'ledger-mini',
    tagline: 'Plain-text accounting CLI',
    description: 'Hobby project: a single-file accounting tool with envelope budgets and CSV import. No active feature work right now.',
    accent: 'slate',
    status: 'paused',
    repo: 'github.com/you/ledger-mini',
    icon: '∎',
    pinned: false,
    lastTouched: '3w ago',
    activeFeatures: 0,
    totalFeatures: 1,
    liveSessions: 0,
    openTickets: 0,
  },
];

const FEATURES = [
  {
    id: 'FEAT-018',
    project: 'PRJ-01',
    slug: 'agent-pane-multiplexer',
    title: 'Agent pane multiplexer',
    vision: 'Run multiple agent sessions in a single tmux window with split-pane navigation, scrollback search, and per-pane state badges.',
    status: 'in-progress',
    milestone: 'v0.4 — Multi-agent',
    target: 'May 12',
    progress: 0.62,
    accent: 'iris',
    health: 'on-track',
    tickets: 8,
    ticketsDone: 5,
    tags: ['terminal', 'agent', 'core'],
    sessions: 3,
    lastTouched: '12m ago',
    pinnedDoc: 'PRD',
  },
  {
    id: 'FEAT-019',
    project: 'PRJ-01',
    slug: 'feature-context-bundle',
    title: 'Feature ↔ session context bundle',
    vision: 'Bind every agent session to its feature\'s PRD, design notes, and acceptance checklist so resuming work loads the full context window.',
    status: 'in-progress',
    milestone: 'v0.4 — Multi-agent',
    target: 'May 19',
    progress: 0.34,
    accent: 'iris',
    health: 'on-track',
    tickets: 6,
    ticketsDone: 2,
    tags: ['agent', 'context', 'docs'],
    sessions: 2,
    lastTouched: '1h ago',
    pinnedDoc: 'PRD',
  },
  {
    id: 'FEAT-020',
    project: 'PRJ-01',
    slug: 'review-diff-checklist',
    title: 'Review surface — diff + acceptance checklist',
    vision: 'A side-by-side diff with the ticket\'s acceptance criteria pinned next to it; approve, request changes, or send back to the agent inline.',
    status: 'review',
    milestone: 'v0.4 — Multi-agent',
    target: 'May 26',
    progress: 0.88,
    accent: 'amber',
    health: 'at-risk',
    tickets: 4,
    ticketsDone: 3,
    tags: ['review', 'ui'],
    sessions: 1,
    lastTouched: '3h ago',
    pinnedDoc: 'Eng design',
  },
  {
    id: 'FEAT-021',
    project: 'PRJ-01',
    slug: 'roadmap-timeline',
    title: 'Roadmap timeline view',
    vision: 'Single horizontal timeline of features by target milestone — drag to reschedule, click to drill in.',
    status: 'planned',
    milestone: 'v0.5 — Planning',
    target: 'Jun 9',
    progress: 0.05,
    accent: 'mint',
    health: 'planned',
    tickets: 3,
    ticketsDone: 0,
    tags: ['ui', 'planning'],
    sessions: 0,
    lastTouched: '2d ago',
    pinnedDoc: 'Vision',
  },
  {
    id: 'FEAT-022',
    project: 'PRJ-01',
    slug: 'decisions-log',
    title: 'Per-feature decisions log',
    vision: 'Append-only log of architectural decisions tied to each feature, surfaced into agent context on resume.',
    status: 'planned',
    milestone: 'v0.5 — Planning',
    target: 'Jun 16',
    progress: 0,
    accent: 'mint',
    health: 'planned',
    tickets: 2,
    ticketsDone: 0,
    tags: ['docs', 'context'],
    sessions: 0,
    lastTouched: '5d ago',
    pinnedDoc: 'Notes',
  },
  {
    id: 'FEAT-017',
    project: 'PRJ-01',
    slug: 'sqlite-store',
    title: 'SQLite store + migrations',
    vision: 'Local SQLite-backed persistence with auto-migration on boot. No external db dependency.',
    status: 'shipped',
    milestone: 'v0.3 — Persistence',
    target: 'Apr 14',
    progress: 1,
    accent: 'slate',
    health: 'shipped',
    tickets: 5,
    ticketsDone: 5,
    tags: ['infra', 'storage'],
    sessions: 0,
    lastTouched: '11d ago',
    pinnedDoc: 'Eng design',
  },
  // sift project
  {
    id: 'FEAT-031',
    project: 'PRJ-02',
    slug: 'structured-query-grammar',
    title: 'Structured query grammar',
    vision: 'Parser for filter expressions like `level:error path:~/work` with autocomplete and saved queries.',
    status: 'in-progress',
    milestone: 'v0.2 — Query',
    target: 'May 5',
    progress: 0.41,
    accent: 'amber',
    health: 'on-track',
    tickets: 5,
    ticketsDone: 2,
    tags: ['parser', 'query'],
    sessions: 0,
    lastTouched: '2d ago',
    pinnedDoc: 'PRD',
  },
  {
    id: 'FEAT-032',
    project: 'PRJ-02',
    slug: 'incremental-indexer',
    title: 'Incremental indexer',
    vision: 'Watch log directories and update the local index without re-scanning. Dedup via inode + offset.',
    status: 'planned',
    milestone: 'v0.3 — Index',
    target: 'May 28',
    progress: 0,
    accent: 'amber',
    health: 'planned',
    tickets: 4,
    ticketsDone: 0,
    tags: ['infra', 'fs'],
    sessions: 0,
    lastTouched: '1w ago',
    pinnedDoc: 'Notes',
  },
  // paper-cuts project
  {
    id: 'FEAT-040',
    project: 'PRJ-03',
    slug: 'footnote-popovers',
    title: 'Footnote popovers',
    vision: 'Inline preview popovers for footnotes on hover, falling back to anchor scroll on touch.',
    status: 'planned',
    milestone: 'v1.4 — Reading',
    target: 'Jun 2',
    progress: 0.1,
    accent: 'mint',
    health: 'planned',
    tickets: 2,
    ticketsDone: 0,
    tags: ['ui', 'reading'],
    sessions: 0,
    lastTouched: '6d ago',
    pinnedDoc: 'Notes',
  },
];

// Tickets — auto-numbered globally, branch field is derived not authored.
const TICKETS = [
  // sift tickets
  { id: 'TMX-0061', feature: 'FEAT-031', title: 'Lex tokens + grammar', status: 'doing', sessions: 0, branch: 'feat/tmx-0061-lex', criteria: 4, criteriaDone: 2, updated: '2d ago', estimate: 'M' },
  { id: 'TMX-0062', feature: 'FEAT-031', title: 'Autocomplete provider', status: 'todo', sessions: 0, branch: null, criteria: 3, criteriaDone: 0, updated: '3d ago', estimate: 'S' },
  { id: 'TMX-0063', feature: 'FEAT-031', title: 'Saved-query store', status: 'todo', sessions: 0, branch: null, criteria: 3, criteriaDone: 0, updated: '4d ago', estimate: 'S' },
  { id: 'TMX-0070', feature: 'FEAT-040', title: 'Hover popover component', status: 'todo', sessions: 0, branch: null, criteria: 2, criteriaDone: 0, updated: '6d ago', estimate: 'S' },
  // tmux-agent tickets
  { id: 'TMX-0042', feature: 'FEAT-018', title: 'Pane registry + lifecycle hooks', status: 'doing', sessions: 1, branch: 'feat/tmx-0042-pane-registry', criteria: 4, criteriaDone: 2, updated: '12m ago', estimate: 'M' },
  { id: 'TMX-0043', feature: 'FEAT-018', title: 'Split layout grammar (h/v/grid)', status: 'doing', sessions: 1, branch: 'feat/tmx-0043-split-grammar', criteria: 5, criteriaDone: 3, updated: '34m ago', estimate: 'L' },
  { id: 'TMX-0044', feature: 'FEAT-018', title: 'Per-pane status badge stream', status: 'review', sessions: 1, branch: 'feat/tmx-0044-status-badge', criteria: 3, criteriaDone: 3, updated: '1h ago', estimate: 'S' },
  { id: 'TMX-0045', feature: 'FEAT-018', title: 'Scrollback search (regex + jump)', status: 'todo', sessions: 0, branch: null, criteria: 4, criteriaDone: 0, updated: 'yesterday', estimate: 'M' },
  { id: 'TMX-0046', feature: 'FEAT-018', title: 'Keyboard map: pane navigation', status: 'todo', sessions: 0, branch: null, criteria: 3, criteriaDone: 0, updated: 'yesterday', estimate: 'S' },
  { id: 'TMX-0047', feature: 'FEAT-019', title: 'Context bundle schema', status: 'doing', sessions: 1, branch: 'feat/tmx-0047-context-bundle', criteria: 5, criteriaDone: 4, updated: '1h ago', estimate: 'M' },
  { id: 'TMX-0048', feature: 'FEAT-019', title: 'PRD/notes resolver per session', status: 'doing', sessions: 1, branch: 'feat/tmx-0048-prd-resolver', criteria: 4, criteriaDone: 1, updated: '3h ago', estimate: 'M' },
  { id: 'TMX-0049', feature: 'FEAT-019', title: 'Resume hook → re-inject context', status: 'todo', sessions: 0, branch: null, criteria: 3, criteriaDone: 0, updated: '2d ago', estimate: 'S' },
  { id: 'TMX-0050', feature: 'FEAT-020', title: 'Diff viewer component', status: 'review', sessions: 1, branch: 'feat/tmx-0050-diff-viewer', criteria: 6, criteriaDone: 6, updated: '3h ago', estimate: 'L' },
  { id: 'TMX-0051', feature: 'FEAT-020', title: 'Acceptance checklist binding', status: 'review', sessions: 0, branch: 'feat/tmx-0051-checklist', criteria: 4, criteriaDone: 4, updated: '4h ago', estimate: 'S' },
  { id: 'TMX-0052', feature: 'FEAT-020', title: 'Approve / request-changes actions', status: 'doing', sessions: 1, branch: 'feat/tmx-0052-review-actions', criteria: 3, criteriaDone: 2, updated: '6h ago', estimate: 'S' },
];

// Activity feed — mostly agent activity, some human actions interleaved.
const ACTIVITY = [
  { id: 'a1', actor: 'agent', name: 'session-04', verb: 'pushed 3 commits', target: 'TMX-0042', detail: 'pane registry skeleton + tests', when: '12m', kind: 'commit' },
  { id: 'a2', actor: 'agent', name: 'session-04', verb: 'updated checklist', target: 'TMX-0042', detail: '2/4 acceptance criteria met', when: '14m', kind: 'check' },
  { id: 'a3', actor: 'agent', name: 'session-07', verb: 'opened review', target: 'TMX-0050', detail: '+412 / −37 across 9 files', when: '32m', kind: 'review' },
  { id: 'a4', actor: 'human', name: 'you', verb: 'edited PRD', target: 'FEAT-019', detail: '“Resume hook re-injects last 200 lines”', when: '1h', kind: 'doc' },
  { id: 'a5', actor: 'agent', name: 'session-05', verb: 'logged decision', target: 'FEAT-019', detail: 'use slug+sha as bundle key, not branch', when: '1h', kind: 'decision' },
  { id: 'a6', actor: 'agent', name: 'session-07', verb: 'requested input', target: 'TMX-0050', detail: '“Use unified diff or split? defaulting to split.”', when: '2h', kind: 'question' },
  { id: 'a7', actor: 'agent', name: 'session-04', verb: 'ran tests', target: 'TMX-0043', detail: 'go test ./... — 142 passed, 0 failed', when: '3h', kind: 'test' },
  { id: 'a8', actor: 'human', name: 'you', verb: 'approved', target: 'TMX-0044', detail: 'merged into FEAT-018', when: '4h', kind: 'approve' },
  { id: 'a9', actor: 'agent', name: 'session-05', verb: 'drafted spec', target: 'FEAT-019', detail: 'Eng design v2 — 8 sections, 1.4k words', when: '5h', kind: 'doc' },
  { id: 'a10', actor: 'agent', name: 'session-07', verb: 'rebased', target: 'TMX-0051', detail: 'on FEAT-020 head, no conflicts', when: '6h', kind: 'commit' },
];

const SESSIONS = [
  { id: 'session-04', ticket: 'TMX-0042', feature: 'FEAT-018', state: 'idle', uptime: '2h 14m', pane: 'agent:0.0', cpu: 2 },
  { id: 'session-05', ticket: 'TMX-0047', feature: 'FEAT-019', state: 'awaiting-input', uptime: '4h 02m', pane: 'agent:1.0', cpu: 0 },
  { id: 'session-07', ticket: 'TMX-0050', feature: 'FEAT-020', state: 'active', uptime: '47m', pane: 'agent:2.0', cpu: 31 },
  { id: 'session-08', ticket: 'TMX-0048', feature: 'FEAT-019', state: 'active', uptime: '22m', pane: 'agent:1.1', cpu: 18 },
];

// Roadmap milestones — for the timeline strip.
const MILESTONES = [
  { id: 'v0.3', label: 'v0.3 — Persistence', start: 'Apr 1', end: 'Apr 14', state: 'shipped' },
  { id: 'v0.4', label: 'v0.4 — Multi-agent', start: 'Apr 15', end: 'May 26', state: 'active' },
  { id: 'v0.5', label: 'v0.5 — Planning', start: 'May 27', end: 'Jun 23', state: 'planned' },
  { id: 'v0.6', label: 'v0.6 — Polish', start: 'Jun 24', end: 'Jul 21', state: 'planned' },
];

const STATUS_LABEL = {
  todo: 'Todo',
  doing: 'In progress',
  review: 'In review',
  done: 'Done',
  planned: 'Planned',
  'in-progress': 'In progress',
  shipped: 'Shipped',
};

Object.assign(window, { PROJECTS, FEATURES, TICKETS, ACTIVITY, SESSIONS, MILESTONES, STATUS_LABEL, NOW });
